# Generated by Django 5.2 on 2025-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('GCASH', 'GCash'), ('PAYMAYA', 'Maya'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash at Terminal'), ('7ELEVEN', '7-Eleven'), ('GRABPAY', 'GrabPay'), ('COINS_PH', 'Coins.ph')], max_length=50),
        ),
    ]
