# Generated by Django 5.2 on 2025-04-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_system', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
