# Generated by Django 5.2 on 2025-04-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['departure_date', 'departure_time']},
        ),
    ]
